### ISSUE TITLE
[TIP] add an empty #define SketcherExport to your SketcherGlobal.h

### ISSUE THREAD

**Issue by LowLevelMahn** [Salusoft89/planegcs#7]
like:

`#define SketcherExport`

...this way its just a (tiny)little bit more easier to diff/merge with original planegcs

**Comment by thes01** [comment]
Hello :) I see your point, however I think I did it on purpose because the macro was not working well with the C++ treesitter parser. I'll look at it again, though.

**Comment by thes01** [comment]
Ok anyway, I don't see the point of creating the SketcherGlobal.h only for the diff purposes (anyway the original SketcherGlobal.h includes yet another header that also would have to be included or removed using patch or so..). And also I'd neet to move it in the folder structure into the planegcs/headers folder. 

I usually see the diff best when I run the `npm run update-freecad` script and see the diff in the uncommited git changes.
(Just note that there are some little patches that are not yet automated and need to be done by hand).

**Comment by LowLevelMahn** [comment]
thanks for your feedback
